
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: 03_los_goolge_api_utils.ipynb

import os
import googlemaps
from datetime import datetime

# Setup google elevation api key
GCP_MAP_KEY = os.environ.get('GCP_ELEVATION_API')
gmaps = googlemaps.Client(key=GCP_MAP_KEY)


def get_direction_info(direction):
    try:
        travel_dur = direction[0]['legs'][0]['duration']['value']
        travel_len = direction[0]['legs'][0]['distance']['value']
        return [travel_dur, travel_len]
    except:
        return [0, 0]

def collect_google_los(gmap, orig, dest, mode, departure_time=None):
    """
    This function collect level of service (travel time) from HERE APIs

    Parameters
        gmap: googlemaps Client object
        orig: origin location as a [lattitue, longtitude] list
        dest: destination location as a [lattitue, longtitude] list
        mode: travel mode like 'transit', 'driving', 'walking', 'bicycling'
        departure_time: the trip's departure time in datetime format
    Return
        duration (senconds), len (meter)
    """
    direction = gmap.directions(orig, dest, mode=mode, departure_time=departure_time)
    res = get_direction_info(direction)
    return res